spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog-master.xml
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  aop:
    auto: true

server:
  port: 8080

app:
  scheduling:
    mode: none
    enabled: false
    period: 10000
    priceIncreasePercentage: 1.25
    optimization:
      enabled: false
      exclusiveLock: false

currency-service:
  host: http://localhost:8081 #хост второго сервиса
  methods:
    get-exchange-rates: /api/v1/exchange-rates
