spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog-master.xml
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

    open-in-view: true

  aop:
    auto: true


server:
  port: 8080

app:
  scheduling:
    mode: none
    enabled: false
    period: 10000
    priceIncreasePercentage: 1.25
    optimization:
      enabled: false
      exclusiveLock: false

rest:
  currency:
    host: http://localhost:8081
    methods:
      get-exchange-rates: /api/v1/exchange-rates
    mock: false
  account:
    host: http://localhost:8081
    methods:
      get-account-number: /api/v1/account
  crm:
    host: http://localhost:8081
    methods:
      get-crm-inn: /api/v1/crm