apiVersion: v1
kind: Pod
metadata:
  name: product-service
  labels:
    role: product-service
spec:
  containers:
    - name: product-service
      image: artememelyanov/product-service:v1
      ports:
        - name: product-service
          containerPort: 8000
          protocol: TCP
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "local"
  restartPolicy: Always
